### ISSUE TITLE
Probs don't load in dev environment?

### ISSUE THREAD

**Issue by DaveCole** [zengm-games/universal-draft-lottery-simulator#2]
Awesome app!  I've forked it and am attempting to add an animated slow-reveal of the resulting order of teams when a draft sim is performed; as a commish I video the draft in real time and thought it would be cool to have a feature like that for such things.

The problem I'm running into is that after doing an install and a run-script dev, the table never loads - even if the lottery type is changed, it just stays on "Loading..." - is there something I'm missing?

**Comment by dumbmatter** [comment]
For me it seems to work in dev mode in Chrome but not in Firefox, maybe that's it? If not, give more details about how exactly you're installing and running it, and also look on the browser console for errors.

**Comment by DaveCole** [comment]
Aha!  That was it.  Thanks for the quick response, will close this issue - if you like if I can finish my feature I'll hit you with a pull request.

**Comment by dumbmatter** [comment]
Sure, I'd be interested to see what you come up with! In my video games I have a slow reveal, including play/pause/next buttons to let you control the pace if you want. I could imagine some flashier UI for it too...
